---
title: "Scrape Bible"
author: "Dr. Lema Logamou Seknewna & Sakayo Toadoum Sari"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Required packages
```{r warning=FALSE, message=FALSE}
library(rvest)
library(tidyverse)
library(openxlsx)
```


```{r}
first_verses <- list(
  "GEN.1.SBA2015", "EXO.1.SBA2015", "LEV.1.SBA2015", "NUM.1.SBA2015",
  "DEU.1.SBA2015", "JOS.1.SBA2015", "JDG.1.SBA2015", "RUT.1.SBA2015",
  "1SA.1.SBA2015", "2SA.1.SBA2015", "1KI.1.SBA2015", "2KI.1.SBA2015",
  "1CH.1.SBA2015", "2CH.1.SBA2015", "EZR.1.SBA2015", "NEH.1.SBA2015",
  "EST.1.SBA2015", "JOB.1.SBA2015", "PSA.1.SBA2015", "PRO.1.SBA2015",
  "ECC.1.SBA2015", "SNG.1.SBA2015", "ISA.1.SBA2015", "JER.1.SBA2015",
  "LAM.1.SBA2015", "EZK.1.SBA2015", "DAN.1.SBA2015", "HOS.1.SBA2015",
  "JOL.1.SBA2015", "AMO.1.SBA2015", "OBA.1.SBA2015", "JON.1.SBA2015",
  "MIC.1.SBA2015", "NAM.1.SBA2015", "HAB.1.SBA2015", "ZEP.1.SBA2015",
  "HAG.1.SBA2015", "ZEC.1.SBA2015", "MAL.1.SBA2015", "MAT.1.SBA2015",
  "MRK.1.SBA2015", "LUK.1.SBA2015", "JHN.1.SBA2015", "ACT.1.SBA2015",
  "ROM.1.SBA2015", "1CO.1.SBA2015", "2CO.1.SBA2015", "GAL.1.SBA2015",
  "EPH.1.SBA2015", "PHP.1.SBA2015", "COL.1.SBA2015", "1TH.1.SBA2015",
  "2TH.1.SBA2015", "1TI.1.SBA2015", "2TI.1.SBA2015", "TIT.1.SBA2015",
  "PHM.1.SBA2015", "HEB.1.SBA2015", "JAS.1.SBA2015", "1PE.1.SBA2015",
  "2PE.1.SBA2015", "1JN.1.SBA2015", "2JN.1.SBA2015", "3JN.1.SBA2015",
  "JUD.1.SBA2015", "REV.1.SBA2015"
)

# function that will detect the next verse if it exists
prev_verse <- first_verses_fr[[1]]
next_verse <- function(prev_verse){
  v <- strsplit(prev_verse, split = "\\.")[[1]]
  num <- as.numeric(v[2]) + 1
  next_v <- v
  next_v[2] <- num
  next_v <- paste(next_v, collapse = ".")
  return(next_v)
}

sba <- 516
get_all_sba <- lapply(first_verses, function(url){
  verses <- list()
  
  while (TRUE) {
    url_sba <- paste0("https://www.bible.com/bible/", sba, "/", url)
    cat(url, "\n")
  
    links <- read_html(url_sba) %>% html_nodes("a") %>% html_attr("href")
    text <- read_html(url_sba) %>% html_nodes("span") %>% html_text()
    text <- text[text != ""]
    num_indexes <- which(nchar(text) <= 4)
    text <- text[-num_indexes]
    idx_verses <- grep("^[1-9]", text)
    text <- text[idx_verses]
    
    verses[[url]] <- text
    check_next <- grep(url %>% next_verse(), links)
    
    if (length(check_next) != 0){
      cat("The next chapter", url %>% next_verse(), "exists. Getting data ...\n")
      url <- url %>% next_verse()
      url_sba <- paste0("https://www.bible.com/bible/", version, "/", url)
    } else {
      cat("Moving to the next book.\n")
      break
    }
  }
  verses
})
```


## Process the french version
```{r}
first_verses_fr <- first_verses %>% 
  lapply(function(x) gsub("SBA2015", "NEG79", x))

version <- 106

prev_verse %>% next_verse()

get_all_fr <- lapply(first_verses_fr, function(url){
  verses <- list()
  
  while (TRUE) {
    url_fr <- paste0("https://www.bible.com/bible/", version, "/", url)
    cat(url, "\n")
  
    links_fr <- read_html(url_fr) %>% html_nodes("a") %>% html_attr("href")
    text_fr <- read_html(url_fr) %>% html_nodes("span") %>% html_text()
    text_fr <- text_fr[text_fr != ""]
    num_indexes <- which(nchar(text_fr) <= 4)
    text_fr <- text_fr[-num_indexes]
    idx_verses <- grep("^[[:digit:]]+ [A-Z|a-z]", text_fr)
    text_fr <- text_fr[idx_verses]
    text_fr <- text_fr[!grepl("Soci??t?? Biblique de Gen??ve", text_fr)]
    
    verses[[url]] <- text_fr
    check_next <- grep(url %>% next_verse(), links_fr)
    
    if (length(check_next) != 0){
      cat("The next chapter", url %>% next_verse(), "exists. Getting data ...\n")
      url <- url %>% next_verse()
      url_fr <- paste0("https://www.bible.com/bible/", version, "/", url)
    } else {
      cat("Moving to the next book.\n")
      break
    }
  }
  verses
})
```


## Merging data
```{r}
merge_all <- function(x_list){
  x_list_processed <- lapply(x_list, function(list_element){
    n <- names(list_element)
    to_dataframe <- lapply(n, function(i){
      chp_id <- paste0(strsplit(i, split = "\\.")[[1]][1:2], collapse = ".")
      verse_id <- as.numeric(gsub("([0-9]+).*$", "\\1", list_element[[i]]))
      chapter <- data.frame(ChapterID = chp_id, 
                            VerseID = verse_id,
                            Content = list_element[[i]])
    })
  }) %>% bind_rows()
  return(x_list_processed)
}

# Number of verses by chapter


sba_bible <- merge_all(get_all_sba)
fr_bible <- merge_all(get_all_fr)

# Merge all
data <- sba_bible %>% left_join(fr_bible, by = c("ChapterID", "VerseID")) %>% 
  rename(Content_SBA = Content.x, Content_Fr = Content.y)
View(data)


write.xlsx(data, "scrapped_Bible.xlsx")
```


## Detecting matching problems
```{r}
# to be checked manually
to_be_checked <- data %>% filter(is.na(Content_Fr)) %>% 
  select(ChapterID, VerseID)

write.xlsx(to_be_checked, "to_be_checked.xlsx")
```

Solutions:

1. Open the two excel files 

2. Get the verse ID from to_be_checked.xlsx and check what could be the problem in scrapped_Bible.xlsx

3. Copy the missing verse from online bible and paste it to the Excel document.